apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: letsdotech/grpc-client:latest
        env:
        - name: SERVER_ADDRESS
          value: "grpc-server-service:50051"
